<?php
/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * MagicLogin\Dependencies\Twilio - Assistants
 * This is the public MagicLogin\Dependencies\Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MagicLogin\Dependencies\Twilio\Rest\Assistants\V1;

use MagicLogin\Dependencies\Twilio\Options;
use MagicLogin\Dependencies\Twilio\Values;

abstract class ToolOptions
{



    /**
     * @param string $assistantId
     * @return ReadToolOptions Options builder
     */
    public static function read(
        
        string $assistantId = Values::NONE

    ): ReadToolOptions
    {
        return new ReadToolOptions(
            $assistantId
        );
    }


}




class ReadToolOptions extends Options
    {
    /**
     * @param string $assistantId
     */
    public function __construct(
        
        string $assistantId = Values::NONE

    ) {
        $this->options['assistantId'] = $assistantId;
    }

    /**
     * @param string $assistantId
     * @return $this Fluent Builder
     */
    public function setAssistantId(string $assistantId): self
    {
        $this->options['assistantId'] = $assistantId;
        return $this;
    }

    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $options = \http_build_query(Values::of($this->options), '', ' ');
        return '[Twilio.Assistants.V1.ReadToolOptions ' . $options . ']';
    }
}


