<?php

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0
 * /       /
 */

namespace MagicLogin\Dependencies\Twilio\TwiML\Voice;

use MagicLogin\Dependencies\Twilio\TwiML\TwiML;

class ApplicationSid extends TwiML {
    /**
     * ApplicationSid constructor.
     *
     * @param string $sid Application sid to dial
     */
    public function __construct($sid) {
        parent::__construct('ApplicationSid', $sid);
    }
}