<?php

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0
 * /       /
 */

namespace MagicLogin\Dependencies\Twilio\TwiML\Voice;

use MagicLogin\Dependencies\Twilio\TwiML\TwiML;

class Sim extends TwiML {
    /**
     * Sim constructor.
     *
     * @param string $simSid SIM SID
     */
    public function __construct($simSid) {
        parent::__construct('Sim', $simSid);
    }
}