<?php

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0
 * /       /
 */

namespace MagicLogin\Dependencies\Twilio\TwiML\Video;

use MagicLogin\Dependencies\Twilio\TwiML\TwiML;

class Room extends TwiML {
    /**
     * Room constructor.
     * 
     * @param string $name Room name
     */
    public function __construct($name) {
        parent::__construct('Room', $name);
    }
}